- name: Update system
  become: yes
  dnf:
    name: '*'
    state: latest

- name: Install core workstation packages
  become: yes
  dnf:
    name:
    - '@Multimedia'
    - vim
    - imwheel
    - wget
    - unzip
    - xclip
    - curl
    - clang
    - sensible-utils
    - xdotool
    - screenkey
    - compton
    - redshift
    - urlview
    - xbacklight
    - playerctl
    - ncdu
    - tldr
    - redshift
    - peek
    - syncthing # config?
    - awesome
    # TODO check if this is working fine
    - yarnpkg


- name: Install rpmfusion repositories
  become: yes
  dnf:
    disable_gpg_check: yes
    name:
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
#
#
#
# - name: Importing (free) key
#   ansible.builtin.rpm_key:
#     state: present
#     key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2021
#
# - name: Importing (non-free) key
#   ansible.builtin.rpm_key:
#     state: present
#     key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2021
