- name: Install syncthing
  become: yes
  dnf:
    name:
    - syncthing

- name: Start Syncthing service
  ansible.builtin.systemd:
    name: "syncthing"
    enabled: yes
    state: started
    scope: user
