- name: Install core GUI apps
  become: yes
  dnf:
    name:
    - thunderbird
    - deluge
    - alacritty
    - easyeffects
    - pavucontrol
    - greybird-dark-theme
    - lxappearance
    - seahorse
    - zathura
    - zathura-pdf-poppler
    - gimp
