- name: Install core GUI apps
  become: yes
  dnf:
    name:
    - thunderbird
    - deluge
    - alacritty
    - easyeffects
    - pavucontrol
    - greybird-dark-theme
    - lxappearance
    - seahorse
    - zathura
    - zathura-pdf-poppler
    - gimp

- name: Install zoom rpm
  become: yes
  dnf:
     name: https://zoom.us/client/latest/zoom_x86_64.rpm
     disable_gpg_check: yes
     state: present

