- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    method: user
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install teams flatpak
  community.general.flatpak:
    method: user
    name: com.github.IsmaelMartinez.teams_for_linux

- name: Install spotify flatpak
  community.general.flatpak:
    method: user
    name: com.spotify.Client

- name: Install skype flatpak
  community.general.flatpak:
    method: user
    name: com.skype.Client

- name: Install zoom flatpak
  community.general.flatpak:
    method: user
    name: us.zoom.Zoom

- name: Install telegram flatpak
  community.general.flatpak:
    method: user
    name: org.telegram.desktop

- name: Install discord flatpak
  community.general.flatpak:
    method: user
    name: com.discordapp.Discord

