- name: Register gh-cli repo
  ansible.builtin.shell:
    cmd: dnf repolist | grep gh-cli
    warn: no
  ignore_errors: yes
  changed_when: false
  register: gh_cli_repo

- name: Add repo for Github command line utility
  become: yes
  ansible.builtin.shell:
    cmd: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
    warn: no
  when: gh_cli_repo.stdout == 0

- name: Install git and git-related tools
  become: yes
  dnf:
    name:
    - git
    - git-credential-libsecret
    - git-delta
    - gh
