- name: Add repo for Github command line utility
  become: yes
  ansible.builtin.shell:
    cmd: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
    warn: no

- name: Install git and git-related tools
  become: yes
  dnf:
    name:
    - git
    - git-credential-libsecret
    - git-delta
    - gh
