- name: Install Kmonad deps
  become: yes
  dnf:
    name:
    - stack

- name: Register kmonad repo
  stat:
    path: ~/repos/kmonad
  register: kmonad_repo

- name: Clone Kmonad
  ansible.builtin.git:
    repo: https://github.com/kmonad/kmonad.git
    dest: ~/repos/kmonad
  when: not kmonad_repo.stat.exists

- name: Register kmonad executable
  stat:
    path: ~/.local/bin/kmonad
  register: kmonad_executable

- name: Build Kmonad
  shell: stack install
  args:
    chdir: ~/repos/kmonad
    creates: ~/.local/bin/kmonad
  when: not kmonad_executable.stat.exists

- name: Add user to input and uinput groups
  become: yes
  shell: |
    groupadd -f uinput
    usermod -aG input $USER
    usermod -aG uinput $USER

- name: Register uinput rules
  stat:
    path: /etc/udev/rules.d/90-uinput.rules
  register: uinput_rules

- name: Creating a file with content
  become: yes
  copy:
    dest: /etc/udev/rules.d/90-uinput.rules
    content: |
      KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
  when: uinput_rules.stat.exists

- name: Enable uinput kernel module
  become: yes
  shell: >
    echo uinput > /etc/modules-load.d/uinput.conf

- name: Start Kmonad service
  ansible.builtin.systemd:
    name: kmonad
    enabled: yes
    state: started
    scope: user
  when: not kmonad_executable.stat.exists
