- name: Install Kmonad deps
  become: yes
  dnf:
    name:
    - stack

- name: Clone Kmonad
  ansible.builtin.git:
    repo: https://github.com/kmonad/kmonad.git
    dest: ~/repos/kmonad

- name: Build Kmonad
  shell: stack install
  args:
    chdir: ~/repos/kmonad
    creates: ~/.local/bin/kmonad

- name: Add user to input and uinput groups
  become: yes
  shell: |
    groupadd -f uinput
    usermod -aG input $USER
    usermod -aG uinput $USER

- name: Add uinput rules
  become: yes
  shell: >
    echo 'KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"' > /etc/udev/rules.d/90-uinput.rules

- name: Enable uinput kernel module
  become: yes
  shell: >
    echo uinput > /etc/modules-load.d/uinput.conf

# udevadm control --reload-rules ; udevadm trigger
# modprobe --first-time uinput -- this command was failing before reboot https://github.com/kmonad/kmonad/issues/160
# this will fail, reboot is needed or some fancy command
- name: Start Kmonad service
  ansible.builtin.systemd:
    name: kmonad
    enabled: yes
    state: started
    scope: user


