- name: Install neovim
  become: yes
  dnf:
    name: neovim

# - name: Sync neovim plugins
#   # This is not correct
#   shell: nvim --headless -c 'quitall'

- name: Install npm dependencies for neovim
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop:
    - js-beautify
    - stylelint
    - marked
    - vscode-json-languageserver
    - bash-language-server
    - vscode-langservers-extracted
    - sql-language-server
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - diagnostic-languageserver
    - @tailwindcss/language-server

- name: Install denojs
  ansible.builtin.shell: curl -fsSL https://deno.land/x/install/install.sh | sh
  args:
    creates: ~/.deno/bin/deno
