- name: Install neovim build dependencies
  become: yes
  dnf:
    name:
    - ninja-build
    - libtool
    - autoconf
    - automake
    - cmake
    - gcc
    - gcc-c++
    - make
    - pkgconfig
    - unzip
    - patch
    - gettext
    - curl

- name: Register neovim repo
  stat:
    path: "$EXT_XDG_REPOS_DIR/neovim"
  register: neovim_repo

- name: Clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    depth: 50
    version: stable
    dest: "$EXT_XDG_REPOS_DIR/neovim"
  when: not neovim_repo.stat.exists

- name: Pull latest neovim
  ansible.builtin.shell: >
    git checkout stable
    git pull
  args:
    chdir: "$EXT_XDG_REPOS_DIR/neovim"

- name: Build neovim from source
  become: yes
  make:
    chdir: /home/vik/repos/neovim
    target: install
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install npm dependencies for neovim
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop:
    - js-beautify
    - stylelint
    - marked
    - bash-language-server
    - vscode-langservers-extracted
    - sql-language-server
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - diagnostic-languageserver
    - '@tailwindcss/language-server'

- name: Install denojs
  ansible.builtin.shell: curl -fsSL https://deno.land/x/install/install.sh | sh
  args:
    creates: ~/.deno/bin/deno

- name: Run packer sync
  ansible.builtin.shell: "nvim +PackerSync +qall"

