- name: Tools
  hosts: "{{ var_hosts }}"
  vars_files:
  - "../vars.yml"
  remote_user: "{{ username }}"
  tasks:
    - include: ../tasks/tools/lua.yml
    - include: ../tasks/tools/node.yml
    - include: ../tasks/tools/tmux.yml
    - include: ../tasks/tools/zk.yml

    - name: Install kmonad?
      include_tasks: ../tasks/tools/kmonad.yml
      when: install_kmonad

    - include: ../tasks/tools/git.yml
    - include: ../tasks/tools/neovim.yml
    # - include: ../tasks/tools/postgres.yml
    - include: ../tasks/tools/elasticsearch.yml
    - include: ../tasks/tools/mysql.yml
    - include: ../tasks/tools/redis.yml
    - include: ../tasks/tools/docker.yml
    - include: ../tasks/tools/dotfiles.yml

